# Generated by Django 4.0.1 on 2022-01-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HamsterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=350)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='hamster_images/%Y/%m')),
            ],
            options={
                'verbose_name': 'Really cute hamster',
                'verbose_name_plural': 'Really cute hamsters',
            },
        ),
        migrations.CreateModel(
            name='WeightRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_in_grams', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('hamster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamsterapp.hamstermodel')),
            ],
            options={
                'verbose_name': 'weight record',
                'verbose_name_plural': 'weight records',
            },
        ),
    ]
