# Generated by Django 3.2.12 on 2022-02-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latin_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('typical_weight', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='HamsterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=350)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='hamster_images/%Y/%m')),
                ('hamster_secret', models.TextField(blank=True)),
                ('height', models.PositiveSmallIntegerField(verbose_name='height (cm)')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hamsterapp.speciesmodel')),
            ],
            options={
                'verbose_name': 'Really cute hamster',
                'verbose_name_plural': 'Really cute hamsters',
            },
        ),
    ]
