# Generated by Django 4.0.1 on 2022-01-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hamsterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latin_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('typical_weight', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
            },
        ),
        migrations.AddField(
            model_name='hamstermodel',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hamsterapp.speciesmodel'),
        ),
    ]
