# Generated by Django 4.0.1 on 2022-02-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsterapp', '0002_speciesmodel_hamstermodel_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamstermodel',
            name='hamster_secret',
            field=models.TextField(blank=True),
        ),
    ]
