# Generated by Django 4.0.1 on 2022-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsterapp', '0003_hamstermodel_hamster_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamstermodel',
            name='height',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='height (cm)'),
            preserve_default=False,
        ),
    ]
