# Generated by Django 3.2.12 on 2022-02-21 16:53

from django.db import migrations, models
import hamsterapp.models.hamster


class Migration(migrations.Migration):

    dependencies = [
        ('hamsterapp', '0004_hamstermodel_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamstermodel',
            name='image',
            field=models.TextField(default=hamsterapp.models.hamster.get_random_image),
        ),
    ]
